### ISSUE TITLE
Falta de carrito

### ISSUE THREAD

**Issue by Nidev-lab** [Euse1980/trabajofinal-frontend-restaurante-junin#3]
## Proceso

1. Ingrese a la pagina.
2. Agregue uno pedidos al carrito.

## Resultado esperado

• Una vez añadidos los productos al carrito, poder ver mis productos en el carrito.

## Resultado actual

• No se visualiza el carrito por ninguna parte.

## Captura

![image](https://github.com/Euse1980/trabajofinal-frontend-restaurante-junin/assets/53904695/2924ab24-9f49-4608-b576-c8ecf2269e7a)
![image](https://github.com/Euse1980/trabajofinal-frontend-restaurante-junin/assets/53904695/b926ebbb-8a2e-4c1f-9af7-90d4de4b701d)
![image](https://github.com/Euse1980/trabajofinal-frontend-restaurante-junin/assets/53904695/86dd4eb7-1514-404c-9f56-c21b1dc48eab)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Acabo de loguearme con un usuario y si se ve el carrito... Estaría bueno que no se puedan agregar productos al carrito si la persona no esta logueada, sino que el carrito sea visible para todos pero que no se pueda realizar la compra sin estar logueado.

**Comment by Euse1980** [comment]
Corregido
